### ISSUE TITLE
为什么npm start报错

### ISSUE THREAD

**Issue by tony1016** [coolzilj/xueqiu-stock#2]
Uncaught Exception:
TypeError: Cannot read property 'on' of undefined
    at create (/Users/Shared/Project/xueqiu-stock/node_modules/menubar/index.js:27:6)
    at Object.<anonymous> (/Users/Shared/Project/xueqiu-stock/main.js:11:12)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at loadApplicationPackage (/Users/Shared/Project/xueqiu-stock/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/default_app.asar/main.js:253:23)
    at Object.<anonymous> (/Users/Shared/Project/xueqiu-stock/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/default_app.asar/main.js:293:5)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

**Comment by coolzilj** [comment]
目测应该是 menubar 更新了 API 导致的。
这个项目已经不再更新了，
你可以把 package.json 里的
menubar 版本指定为 "2.0.11"，
其他版本没测试过所以不能保证不出错

**Comment by towry** [comment]
https://github.com/towry/xueqiu-stock
